### ISSUE TITLE
Plotting script crashes on empty histograms

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#94] opened 2023-09-07 13:56 UTC
If there are empty histograms, the plotting script can not handle the systematics for them and crashes.
 More specifically, [this line](https://github.com/PocketCoffea/PocketCoffea/blob/759eb6ea9fb75d929726dfc19aa38b7b7ead3f43/pocket_coffea/utils/plot_utils.py#L758) will crash first. Because the `syst_list` will be empty. I was not able to fix this yet, so have to run plotting without systematics.
This should be easy to reproduce by adding the `**electron_hists()` in zmmu example config.

Solution should be to somehow not attempt to calculate systematics for empty plots, but I did not manage to implement this.

**Comment by mmarchegiani** [comment] 2023-10-10 12:59
The issue is addressed in PR #101. When attempting to instantiate a `SystUnc` object from an empty histogram, an exception is raised.

The workaround for this behaviour is to define histograms only for the categories where they should be filled, using the `exclude_categories` option of the `HistConf` constructor, i.e. there should be no need to plot an electron histogram in a category with no electrons.

Example of histogram configuration:
```
"ElectronGood_pt_1_rebin" : HistConf(
            [
                Axis(coll="ElectronGood", field="pt", pos=0, type="variable",
                     bins=bins["ElectronGood_pt"][year],
                     label="Electron $p_{T}$ [GeV]",
                     lim=(0,500))
            ],
            exclude_categories=["SingleMuon_1b", "SingleMuon_2b", "SingleMuon_3b", "SingleMuon_4b"]
        ),
```

In a following PR we could manage this exception at the `Shape` level rather than at the `SystUnc` level.

**Comment by andreypz** [comment] 2023-10-10 13:30
Thanks for addressing this issue.
However, this maybe not the best solution. Sometimes it is useful/necessary to have empty histograms, as a cross check, or validation, or estimate of events in CR, etc. 
Logically, I think it would be better to set `exclude_syst` flag and do not plot the systematic on empty histograms.

**Comment by andreypz** [comment] 2023-11-30 13:31
I again encounter this issue, and I think this issue needs to be re-opened.
User (myself) may not know in advance that the histogram will be empty. And we do not want to crash the plotting script  because of that, an/or require to re-run the full analysis workflow removing the histogram...
It should simply plot an empty histogram.

**Comment by mmarchegiani** [comment] 2023-11-30 14:30
I think your point is reasonable as I also encounter the issue, the histograms can be empty for many reasons (e.g. low statistics in a given category). We can catch this exception when plotting all the data/MC histograms for each category, checking if the data and MC stacks have sumw=0 (I'm thinking of flag attributes of the `Shape` class like `self._has_empty_stack_data` and `self._has_empty_stack_mc` to handle these cases). In these cases, no histogram will be plotted on the figure, but the figure will still be saved.

**Comment by mmarchegiani** [comment] 2023-12-13 13:02
The issue is being addressed in https://github.com/PocketCoffea/PocketCoffea/pull/115: empty histograms are now being plotted and the corresponding image file is saved.

**Closed** 2024-01-11 12:44 UTC
